version: "2"
services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - ./plex/config:/config
      - /Users/anuraag-ws/personalWorkspace/docker_services/mnt:/mnt
    ports:
      - 32401:32400
    restart: unless-stopped
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
    volumes:
      - ./transmission/config:/config
      - /Users/anuraag-ws/personalWorkspace/docker_services/mnt/media/torrents:/mnt/media/torrents
    ports:
      - 9091:9091
      - 49153:49153
      - 49153:49153/udp
    restart: unless-stopped
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - RUN_OPTS=run options here #optional
    volumes:
      - ./jackett/config:/config
      - /Users/anuraag-ws/personalWorkspace/docker_services/mnt/media/torrents/completed:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=PST
      - UMASK_SET=022 #optional
    volumes:
      - ./sonarr/config:/config
      - /Users/anuraag-ws/personalWorkspace/docker_services/mnt/media:/mnt/media
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=PST
    volumes:
      - ./radarr/config:/config
      - /Users/anuraag-ws/personalWorkspace/docker_services/mnt/media:/mnt/media
    ports:
      - 7878:7878
    restart: unless-stopped
  ombi:
    image: linuxserver/ombi
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=PST
      - BASE_URL=/ombi #optional
    volumes:
      - ./ombi/config:/config
    ports:
      - 3579:3579
    restart: unless-stopped