---
version: "2.1"
services:
  duckdns:
    image: lscr.io/linuxserver/duckdns
    container_name: duckdns
    environment:
      - PUID=1001 #optional
      - PGID=1001 #optional
      - TZ=Asia/Kolkata
      - SUBDOMAINS=<>
      - TOKEN=<>
      - LOG_FILE=true #optional
    volumes:
      - ./config:/config #optional
    restart: unless-stopped
