version: '2'

services:
  db:
    image: yobasystems/alpine-mariadb:latest
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - /mnt/usb0/nextcloud/nextcloudd:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=pqssword
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - PUID=0
      - PGID=0

  app:
    image: nextcloud
    ports:
      - 8181:80
    links:
      - db
    volumes:
      - /mnt/usb0/nextcloud/data:/var/www/html
    environment:
      - PUID=0
      - PGID=0
    restart: always
